name: smartcommunity
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  flutter_staggered_grid_view: ^0.4.1
  get: ^4.6.1
  shared_preferences: ^2.0.6
#  wechat_assets_picker: ^7.3.0
#  flutter_inappwebview: ^5.4.3+7
#  url_launcher: ^6.0.20
  flutter_swiper_null_safety: ^1.0.2
  # picker选择器 https://pub.dev/packages/flutter_picker/install
#  flutter_picker: ^2.0.3
  # 刷新控件 https://pub.flutter-io.cn/packages/easy_refresh
  easy_refresh: ^3.0.4+2
  # 刷新 https://pub.flutter-io.cn/packages/pull_to_refresh/install
  pull_to_refresh: ^2.0.0
  # 图片裁剪 https://pub.flutter-io.cn/packages/image_cropper/install
  # image_cropper: ^2.0.3
  # toast组件 https://pub.flutter-io.cn/packages/fluttertoast/install
  fluttertoast: ^8.2.1
  # 列表组件 https://pub.flutter-io.cn/packages/azlistview/install
  azlistview: ^2.0.0
  # 汉字转拼音 https://pub.flutter-io.cn/packages/lpinyin
  lpinyin: ^2.0.2
  # 网络库 https://pub.flutter-io.cn/packages/dio/install
  dio: ^4.0.6
  # 定位 https://pub.flutter-io.cn/packages/geolocator/install
  geolocator: ^9.0.1
  # 加载组件 https://pub.flutter-io.cn/packages/flutter_easyloading/install
  flutter_easyloading: ^3.0.5
  # auto_size_text https://pub.flutter-io.cn/packages/auto_size_text/install
  auto_size_text: ^3.0.0
  # webview https://pub.flutter-io.cn/packages/webview_flutter/install
  webview_flutter: ^3.0.4
#  #webview插件 https://pub.flutter-io.cn/packages/flutter_webview_plugin/install
#  flutter_webview_plugin: ^0.4.0
  # 二维码扫描 https://pub.flutter-io.cn/packages/qr_code_scanner/install
  qr_code_scanner: ^1.0.1
  #权限 https://pub.flutter-io.cn/packages/permission_handler/install
  permission_handler: ^10.1.0
  # 相册选择照片或拍照 https://pub.flutter-io.cn/packages/image_picker/install
  image_picker: ^0.8.6
  # 相册选择照片 https://pub.dev/packages/wechat_assets_picker/install
  wechat_assets_picker: ^8.1.3
  # picker https://pub.dev/packages/flutter_picker/install
  flutter_picker: ^2.0.5
  # 日期格式转换 https://pub.flutter-io.cn/packages/date_format/install
  date_format: ^2.0.7
  # 微信sdk https://pub.dev/packages/fluwx/install
  fluwx: 3.8.4
  # 支付宝sdk https://pub.flutter-io.cn/packages/tobias/install
  tobias: ^2.4.1
  # 吸顶 https://pub.flutter-io.cn/packages/extended_nested_scroll_view/install
  extended_nested_scroll_view: ^5.1.3
  # 上拉加载更多 https://pub.flutter-io.cn/packages/loading_more_list/install
  loading_more_list: ^5.0.2
  # 刷新 https://pub.flutter-io.cn/packages/custom_refresh_indicator/install
  custom_refresh_indicator: ^2.0.0
  # 下拉刷新 https://pub.flutter-io.cn/packages/pull_to_refresh_notification/install
  pull_to_refresh_notification: any
  # intl https://pub.flutter-io.cn/packages/intl/install
  intl: any
  # 日志 https://pub.flutter-io.cn/packages/logger/install
  logger: ^1.1.0
  # 事件通知处理 https://pub.flutter-io.cn/packages/event_bus/install
  event_bus: ^2.0.0
  # url_launcher https://pub.flutter-io.cn/packages/url_launcher/install
  url_launcher: ^6.1.7
  # 私有UI库
  sc_uikit:
    git:
      url: http://10.100.10.22/jizuo-flutter/flutter_library/sc_uikit.git
      ref: '0.0.4'

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - images/guide/
    - images/logo/
    - images/login/
    - images/appList/
    - images/mine/
    - images/common/
    - images/goods/
    - images/skin/
    - images/loading/
    - images/scan/
    - images/message/
    - images/coupon/
    - json/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
